### ISSUE TITLE
Providing different covariates for different populations during dreamletCompareClusters

### ISSUE THREAD

**Issue by leqi0001** [GabrielHoffman/dreamlet#11]
Hi,

Thanks for the awesome package! 

I'm trying to compare two populations from the same samples using dreamletCompareClusters. The problem is that I'm trying to provide different covariates for different populations within the same sample, for stuff like picard QC metrics generated for population-specific bam files. If I'm not mistaken, dreamlet only reads the shared sample-specific metadata. I can get around the problem by using regular voomWithDreamWeights() and dream(), but it won't use the cell number when estimating the precision weights. Are there any ways to manually feed separate covariates to dreamletCompareClusters()?

**Comment by GabrielHoffman** [comment]
This is supported for the `dreamlet()` function see [here](https://diseaseneurogenomics.github.io/dreamlet/articles/cell_covs.html).  It is 90% implemented for `dreamletCompareClusters()`.  I'm working on adding this feature.  I'll let you know when its finished

Gabriel

**Comment by leqi0001** [comment]
Thank you Dr. Hoffman. This would do. It seems like the formula specified in dreamletCompareCluster() wouldn't make a huge difference in weight estimation.

**Comment by GabrielHoffman** [comment]
This suggestion is included in `dreamlet >= 0.99.22`
