### ISSUE TITLE
feature request: plot normalized expression values

### ISSUE THREAD

**Issue by xanibas** [GabrielHoffman/dreamlet#12]
Fantastic package! I have a small request, could you add a function to extract normalized expression values (for boxplots for instance). I wrote code to do that myself but would be nice to have it out of the box.

**Comment by xanibas** [comment]
I mean a function to extract the pseudobulk normalized logcounts per sample and cell type (ie from assay(res,x)$E). Would be quite practical for plotting the original normalized values.

**Comment by GabrielHoffman** [comment]
Thanks for the feature request.  Here is the current way to extract the information you want:

```r
library(muscat)
library(dreamlet)
 
 data(example_sce)
 
 # create pseudobulk for each sample and cell cluster
 pb <- aggregateToPseudoBulk(example_sce,
   assay = "counts",
   cluster_id = "cluster_id",
   sample_id = "sample_id",
   verbose = FALSE
 )
 
 # voom-style normalization
 res.proc <- processAssays(pb, ~group_id)

# current syntax to extract normalized expression values
res.proc[["B cells"]]$E['MRPL20',]
assay(res.proc, "B cells")$E['MRPL20',]
```
I agree that the last part is not well documented.  I can fix that.  Also the syntax is really ugly.  As far as new syntax, I could add something like:
```r
res.proc["B cells", 'MRPL20',]
getNormExpr(res.proc, "B cells", 'MRPL20')
```
I think `getNormExpr()` would be clearest on the user end.

Thoughts on naming the function for compatibility?

Best, 
Gabriel
