### ISSUE TITLE
About formula for differential expression analysis using dreamlet

### ISSUE THREAD

**Issue by ghost** [GabrielHoffman/dreamlet#16]
Thank you for the excellent method development.

I am very interested in your work and am hoping to apply it to my research. However, I have some confusion regarding the formula in this package. The structure of my data is as follows: I have two groups of data. One consists of 5 individuals in the control group, and the other consists of 7 individuals in the therapy-treated group. I aim to identify cell-type-specific DEGs between these two groups while considering the individual as a random effect. How should I design the formula?

form <- ~ treatment_group + (1|individual)
form <- ~ treatment_group + (1|individual) + 0
Which one is correct? (Here, I am not considering other confounding factors)

**Comment by GabrielHoffman** [comment]
Both formulas are valid.  There are two ways of encoding a categorical variable.  Let's consider a variable `group` with categories `Control` and `Treated`.

1) formula: ` ~ group`
Estimate two parameters: `(Intercept)` and `groupTreated`.  `(Intercept)` is the overall mean, and `groupTreated` is the estimated effect size of the treated group compared to the control group.  Statistically, you want to test if the coefficient for `groupTreated` is different from zero.

2) formula: ` ~ group + 0`
This coding also estimates two parameters: `groupControl` and `groupTreated`
These are the mean expression for each group.  You are interested in the treatment effect, so you need to test the *difference* between these parameters `groupTreated  - groupControl` using regression contrasts.

These codings are equivalent and will give same effect size and p-values.  Just remember that the interpretation of `groupTreated` is different in the two codings.
