### ISSUE TITLE
question about AIC calculation

### ISSUE THREAD

**Issue by jenellewallace** [GabrielHoffman/dreamlet#20]
Hi, I’m trying to compare several closely related dreamlet models - one with a simple linear term for experimental timepoint, one that treats timepoint as categorical (I have only three timepoints), and one with linear and quadratic terms (as you nicely described here https://diseaseneurogenomics.github.io/dreamlet/articles/non_lin_eff.html). Would you recommend using AIC scores for this? If so, can you give me guidance on how to calculate this correctly for dreamlet objects? I was planning to look at the median AIC score across all genes for each model. Also open to suggestions if there is a different strategy or metric that might be better. What I tried:
- Using limma::selectModel with the design matrix from my res.dl object. However, I was not sure if the calculation is correct for dreamlet objects (I don’t think it includes random effects parameters?).
- Calculating manually using the formula for AIC and the logLik slot in the res.dl object. I was just wondering exactly how to calculate the number of parameters - is this just equal to the number of fixed and random effects parameters or are there additional parameters that should be added related to the limma-voom method? Is there a way to get the number of parameters from the res.dl object (in case some variables were dropped for certain cell types, for example)?
Thank you!!

**Comment by GabrielHoffman** [comment]
Hi Janelle, 
This is almost built in:

```r
library(muscat)
library(SingleCellExperiment)
library(dreamlet)

data(example_sce)

pb <- aggregateToPseudoBulk(example_sce,
  assay = "counts",
  cluster_id = "cluster_id",
  sample_id = "sample_id",
  verbose = FALSE
)

# voom-style normalization
res.proc <- processAssays(pb, ~group_id)

# Differential expression analysis within each assay,
# evaluated on the voom normalized data
res.dl <- dreamlet(res.proc, ~group_id)

# see assays
assayNames(res.dl)

# extract dream fit of B cells 
# from dreamlet fit of multipel cell types
fit = res.dl[["B cells"]]

# get BIC for each gene for "B cells"
BIC(fit)[1:3]

# get number of parameters
# Fit fixed effects model, this is an integer
# for mixed models, it is more complicated
df.gene = rowSums(fit$hatvalues)
df.gene[1:3]

# logLik
logLik(fit)[1:3]
```

**Comment by jenellewallace** [comment]
Great, thanks very much!!
