### ISSUE TITLE
Multiple treatment groups

### ISSUE THREAD

**Issue by jindalk** [GabrielHoffman/dreamlet#21]
Hi, I am trying to use ```dreamlet``` for a dataset with one control and multiple treatment groups per cell type. I wish to compare each treatment group to the same control group. In some other tools, this is achieved by converting the treatment column in the metadata to a factor and setting "Control" as the first level.

Does ```dreamlet``` follow a similar behavior?

Thanks,
Kunal

**Comment by GabrielHoffman** [comment]
Any study design that will work for `limma` will also work in `dreamlet`.  But you say 'dataset with one control', and `limma`/`dreamlet`, etc are only applicable when there is variation _within_ each group.  With only one control, there is no way to estimate the variance within the control group, so a regression approach won't work.

**Comment by jindalk** [comment]
Ah sorry for the confusion. I meant to say my data is grouped into three categories "Treatment 1", "Treatment 2", and "Control", each of them contain multiple samples.
