### ISSUE TITLE
Issues with variance partitioning

### ISSUE THREAD

**Issue by jindalk** [GabrielHoffman/dreamlet#26]
Hi, I have been trying to use variance partitioning to quantify the contribution of various factors in gene expression variance. My formula has a mix of discrete factors, continuous factors, and discrete factors modelled as random effects. However, running `fitVarPart` returns an empty dataframe.

When I run this with smaller subsets of my formula, e.g. `~disease_status + (1|donor)` the analysis returns values for only `disease_status` and `residuals`. Am I doing something wrong here?

Thanks

**Comment by GabrielHoffman** [comment]
This this bug report and fix: https://github.com/GabrielHoffman/dreamlet/issues/25
